// Code generated by hand for scheduler proto. DO NOT EDIT.
// Package proto provides Go bindings for the ExecutorService gRPC service.
// Since protoc is unavailable in this environment, messages are plain Go
// structs serialized via a JSON codec over gRPC.
package proto

import (
	"context"
	"encoding/json"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/encoding"
	"google.golang.org/grpc/status"
)

// --- Messages ---

type TaskRequest struct {
	TaskId   string            `json:"task_id"`
	TaskName string            `json:"task_name"`
	Command  string            `json:"command"`
	Params   map[string]string `json:"params"`
	Timeout  int64             `json:"timeout"`
}

type TaskResponse struct {
	TaskId   string `json:"task_id"`
	Success  bool   `json:"success"`
	Output   string `json:"output"`
	Error    string `json:"error"`
	Duration int64  `json:"duration"`
}

type TaskStatusRequest struct {
	TaskId string `json:"task_id"`
}

type TaskStatusResponse struct {
	TaskId string `json:"task_id"`
	Status string `json:"status"`
	Output string `json:"output"`
	Error  string `json:"error"`
}

type HeartbeatRequest struct {
	ExecutorId string `json:"executor_id"`
	Address    string `json:"address"`
	Capacity   int32  `json:"capacity"`
	Load       int32  `json:"load"`
}

type HeartbeatResponse struct {
	Acknowledged bool `json:"acknowledged"`
}

// --- JSON Codec ---
// Register a JSON codec under a dedicated name. It is only used for the
// scheduler<->executor traffic via grpc.ForceCodec, leaving etcd's default
// protobuf codec untouched.

const CodecName = "scheduler-json"

type jsonCodec struct{}

func (jsonCodec) Name() string { return CodecName }

func (jsonCodec) Marshal(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

func (jsonCodec) Unmarshal(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

// Codec returns the JSON codec used by scheduler-executor gRPC traffic.
func Codec() encoding.Codec { return jsonCodec{} }

func init() {
	encoding.RegisterCodec(jsonCodec{})
}

// --- Service Definition ---

const ExecutorServiceName = "scheduler.ExecutorService"

type ExecutorServiceServer interface {
	ExecuteTask(context.Context, *TaskRequest) (*TaskResponse, error)
	GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

type UnimplementedExecutorServiceServer struct{}

func (UnimplementedExecutorServiceServer) ExecuteTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "ExecuteTask not implemented")
}
func (UnimplementedExecutorServiceServer) GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "GetTaskStatus not implemented")
}
func (UnimplementedExecutorServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "Heartbeat not implemented")
}

// --- Server Registration ---

type executorServiceServer struct {
	ExecutorServiceServer
}

func _ExecutorService_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.ExecutorService/ExecuteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).ExecuteTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.ExecutorService/GetTaskStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).GetTaskStatus(ctx, req.(*TaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.ExecutorService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: ExecutorServiceName,
	HandlerType: (*ExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "ExecuteTask", Handler: _ExecutorService_ExecuteTask_Handler},
		{MethodName: "GetTaskStatus", Handler: _ExecutorService_GetTaskStatus_Handler},
		{MethodName: "Heartbeat", Handler: _ExecutorService_Heartbeat_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "executor.proto",
}

func RegisterExecutorServiceServer(s grpc.ServiceRegistrar, srv ExecutorServiceServer) {
	s.RegisterService(&ExecutorService_ServiceDesc, &executorServiceServer{srv})
}

// --- Client ---

type executorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorServiceClient(cc grpc.ClientConnInterface) ExecutorServiceClient {
	return &executorServiceClient{cc: cc}
}

type ExecutorServiceClient interface {
	ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

func (c *executorServiceClient) ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/scheduler.ExecutorService/ExecuteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, "/scheduler.ExecutorService/GetTaskStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/scheduler.ExecutorService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Ensure interface satisfaction at compile time.
var _ ExecutorServiceServer = (*UnimplementedExecutorServiceServer)(nil)
var _ ExecutorServiceClient = (*executorServiceClient)(nil)
